### ISSUE TITLE
All trackers get added to tier 0 with AddqBittorrentTrackers

### ISSUE THREAD

**Issue by denniskrol** [Jorman/Scripts#18]
qBittorrent 4.5.3 on Windows 10
AddqBittorrentTrackers runs on Ubuntu 22.04

When AddqBittorrentTrackers runs it adds all the trackers without an empty line between them. qBittorrent (and I believe other clients) treat that as 1 tracker that has multiple URLs (tiers). By default the second tracker URL only gets checked when the first tracker URL is unavailable, which means that if the first tracker works, but has no seeders or leechers, and the second tracker does, you can never get those seeders or leechers. 
You can enable [announce_to_all_trackers](https://www.libtorrent.org/reference-Settings.html#announce_to_all_trackers) to get around this by having qBittorrent always announce to all trackers in 1 tier (since all our trackers are now in tier 0), but by default that is disabled.

I tried adding a line break to the cURL command on line [131](https://github.com/Jorman/Scripts/blob/master/AddqBittorrentTrackers.sh#LL131C33-L131C33), but I couldn't get that to work. I don't know if I did that wrong, or if the API trims the tracker URL it gets.

**Comment by Jorman** [comment]
I'm not sure I understand your problem, could you post some screens showing the problem?
It has never occurred to me that a single tracker is added rather than all the individual trackers, even during manual execution you can see that each individual tracker is added separately.
No one then has ever had this problem, which is why I may not really understand what is happening to you.
Are you using the script with the default tracker settings or have you changed something?
```
declare -a live_trackers_list_urls=(
	"https://newtrackon.com/api/stable"
	"https://trackerslist.com/best.txt"
	"https://trackerslist.com/http.txt"
	"https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
	)
```

Let me know

**Comment by denniskrol** [comment]
All the trackers get added to all the torrents, that works fine.
What I mean is [Tracker tiers](http://bittorrent.org/beps/bep_0012.html)

Example tracker list:
```
http://tracker.openbittorrent.com:80/announce

http://tracker1.bt.moack.co.kr:80/announce

http://tracker.mywaifu.best:6969/announce

http://tracker.dler.org:6969/announce

http://fosstorrents.com:6969/announce

http://bt.okmp3.ru:2710/announce

http://www.peckservers.com:9000/announce

http://wepzone.net:6969/announce
```
qBittorrent shows this as
![image](https://github.com/Jorman/Scripts/assets/10570858/b5820818-b142-47c9-acc3-ddf152ccf2cf)
All trackers are in a tier by themselves

When I run the script the trackers get added like this (shortened the list a bit)
```
http://tracker.edkj.club:6969/announce
http://region.nl1.privex.cc:6969/announce
http://tracker.zerobytes.xyz:1337/announce
http://open.8a.is:6969/announce
http://incine.ru:6969/announce
http://www.chouchou.club:8080/announce
http://tracker.sheesh.rip:6969/announce
http://tracker.opentrackr.org:1337/announce
http://ch3oh.ru:6969/announce
http://canardscitrons.nohost.me:6969/announce
http://tracker2.itzmx.com:6961/announce
http://wg.mortis.me:6969/announce
http://uraniumhexafluori.de:1919/announce

http://tracker.openbittorrent.com:80/announce

http://tracker1.bt.moack.co.kr:80/announce

http://open.acgnxtracker.com:80/announce

http://tracker2.dler.org:80/announce

http://tracker.renfei.net:8080/announce
```
![image](https://github.com/Jorman/Scripts/assets/10570858/c6e223f0-a73e-4be7-88e2-065a917dd210)
All the newly added trackers are all in tier 0, because there is no empty line break between them.

With the default qBittorrent options then this happens
![image](https://github.com/Jorman/Scripts/assets/10570858/15a070d6-8f25-4b1e-8ad6-d0585bdccf31)
It will only connect to the second tracker in tier 0, when the first tracker in that tier can't be contacted. Which means that IF the first one in tier 0 works, but has no peers, all the other trackers are never tried, even though they might have peers. I have some private trackers that use this, by having multiple domains for the tracker, but they only want to announce to the tracker once.

This is not the end of the world, I can set [announce_to_all_trackers](https://www.libtorrent.org/reference-Settings.html#announce_to_all_trackers) and qBittorrent will announce to all. But it will then also do this for the private tracker, which might not like announcing multiple times.

**Comment by Jorman** [comment]
Ok, I got your point, never considered this aspect and actually I am not "expert", it is a new topic for me, but I will look into it better. I have some questions/specifications to ask about this, you will see that a "solution" we try to find.
`announce_to_all_trackers` According to the qBittorrent wiki, it is active by default, this would explain why all trackers are always contacted by me, including those in the same tier `https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent`
![image](https://github.com/Jorman/Scripts/assets/5203988/b6c4c9c4-fc63-4138-8859-4adafe5cf612)
To the best of my recollection I never changed the default settings of qBittorrent, so I never noticed the "problem", check it too if you want.

Btw, I'm going to do some testing now, unfortunately this is something I intentionally changed in the script, otherwise when inserting, blank lines would be inserted as well.

I will tell you

**Comment by Jorman** [comment]
I tried in various way and I also wrote one post to qBittorrent discussione git, but for now no reply.
I think that every time I try to inject one or more trackers inside a torrent, every torrent pushed will finish in a Tier 0, even if I change the session.
So for now I'm sorry I can't help in this, I've to wait a reply from qBittorrent git discussion in order to see if this is possible.

I'll leave this open, is not a "real" bug is a kind of leak of functionality, but I think is coming from qBittorrent side

**Comment by denilsonsa** [comment]
According to [their wiki](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-trackers-to-torrent), you can POST multiple trackers in one single request, split by newlines. Thus, what would happen if you posted all the trackers at once, split by two newlines? (The current behavior is to do one POST request per tracker.)
