### ISSUE TITLE
Request: remove old trackers

### ISSUE THREAD

**Issue by omygolly** [Jorman/Scripts#21]
Heya,

Is there an option to make the script clear the current trackers the torrent has before adding the fresh list?

**Comment by tsweet64** [comment]
I often do what OP says on torrents that pull in an absolutely absurd (100+) number of trackers, because I prefer it to make a smaller number of connections to ~10 or so good and robust trackers.

Also, it looks like version 5.0 of qBittorrent will include a feature to remove a specific tracker from all torrents in bulk. https://github.com/qbittorrent/qBittorrent/pull/19681 This will make it easier to remove trackers that are dead.
