### ISSUE TITLE
Simplification of the "unique trackers" logic

### ISSUE THREAD

**Issue by denilsonsa** [Jorman/Scripts#24]
This line looks convoluted: https://github.com/Jorman/Scripts/blob/a795c286f38e31c698b651e4f557ef953d9a14a3/AddqBittorrentTrackers.sh#L59

How about simplifying it?

Do we care about the initial order of the list? If we don't care, we can just use:

```bash
	trackers_list=$(echo "$tmp_trackers_list" | tr ' ' '\n' | sort | uniq)
	# Alternative version that may not work on certain systems:
	trackers_list=$(echo "$tmp_trackers_list" | tr ' ' '\n' | sort -u)
```

If we care about the initial order:

```bash
	trackers_list=$(echo "$tmp_trackers_list" | tr ' ' '\n' | awk '{if ($0 && !a[$0]++) print($0)}')
```

We can even make it print an additional newline, in case that helps with #18:

```bash
	trackers_list=$(echo "$tmp_trackers_list" | tr ' ' '\n' | awk '{if ($0 && !a[$0]++) print($0 "\n")}')
```

String concatenation in awk is accomplished by just putting strings next to each other, no operator needed.

**Comment by Jorman** [comment]
Hi,
thank you for point me out, actually I saw the possibility to send all the trackers list in one single command, but I never take time to analyze better the `trackers_list` string, because the tricky point was here!
Unfortunately, I'm not a professional programmer, so maybe I have the idea, but I have to make a lot of tests and dig the web searching solutions.
So, I take your last solution because this works in order to fix #18, with a simple modification to the injection function
I also checked the performance and the execution time is not so different

Thanks
