### ISSUE TITLE
Trackers injected in private torrent despite using only `-a option`

### ISSUE THREAD

**Issue by soredake** [Jorman/Scripts#34]
Torrent is clearly marked as private:
![изображение](https://github.com/user-attachments/assets/e96f81ff-88c7-47a3-b143-ddb0619a4f91)

Using qbittorrent 4.6.5

**Comment by Jorman** [comment]
Hi, nice to meet you.

I'm not familiar with this screen, however I just tried and no problem here. Can you tel me if you're using the last version?
Can you post some extra data to better understand where is the problem?

**Comment by soredake** [comment]
> Can you tel me if you're using the last version?

Yes, I only recently cloned this repo.

> I'm not familiar with this screen

It's screen from vuetorrent.

> Can you post some extra data to better understand where is the problem?

I've used `sudo docker -it radarr sh`, then `sh /data/AddqBittorrentTrackers.sh`

**Comment by ineednewpajamas** [comment]
Share a screenshot of the trackers tab of the torrent that includes the DHT, LSD, and PeX parts

**Comment by soredake** [comment]
![изображение](https://github.com/user-attachments/assets/df5334e8-936c-4175-ac83-c7bdde43d325)

**Comment by ineednewpajamas** [comment]
If the message on DHT is actually as displayed, the script is behaving correctly. It looks for the word "private". You could try the curl command yourself and see what it returns or if it's just the language setting in like vuetorrent.

**Comment by ineednewpajamas** [comment]
try this from inside the radarr container, make sure to update the variables

```bash
# set values
qbt_host="qbittorrent"
qbt_port="8080"
qbt_username=""
qbt_password=""
hash="" # put in the infohash of the torrent

# login cookie
qbt_cookie=$(curl --silent --fail --show-error --header "Referer: ${qbt_host}:${qbt_port}" --cookie-jar - --data "username=${qbt_username}&password=${qbt_password}" ${qbt_host}:${qbt_port}/api/v2/auth/login)

echo "$qbt_cookie" | curl --silent --fail --show-error --cookie - --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$hash" | jq --raw-output '.[0] | .msg'
```

**Comment by soredake** [comment]
@ineednewpajamas it says "this torrent is private" (in russian)

**Comment by ineednewpajamas** [comment]
screenshot the output please

**Comment by soredake** [comment]
![изображение](https://github.com/user-attachments/assets/1d507810-6619-4c41-afc2-454ea2a42029)

Nothing interesting.

**Comment by soredake** [comment]
I think the problem is that script expect the answer in english, and in my case that anwser comes in russian language.

**Comment by ineednewpajamas** [comment]
The language is why. The script looks for the message to contain the word "private" in english, so working as expected. Although it might be a feature request to instead look for the private flag on the torrent itself.

**Comment by soredake** [comment]
Would be nice if this script can check if torrent is private not relying on language.

**Comment by soredake** [comment]
IIUC there is a way to check if torrent is private in language-agnostic way https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1) 

![изображение](https://github.com/user-attachments/assets/b46b8a71-0810-463e-ae78-5213d08c6fc6)

**Comment by Jorman** [comment]
Hi, I think the problem is the sh interpreter, this script is made for bash, not for sh.
Try to call it without any interpreter, so it will use the bash one that is specified

As I told you, I need to have more information to understand if there is and where is the problem, because this is too little, unfortunately I can't reproduce the problem, I ask you to clone the last script that is on the git, and that I will update shortly to stop the execution via sh, let's see if we find the problem.

Yes, the control is based on the word `private`, now I check if I can change, at the time when the script was born, it was the only way to know if the torrent was private or not, but as I told you, I will look for more info and see if it is possible to "untie" the language from this context, from memory I had asked the qBittorrent team to include other controls, but I never received a reply

**Comment by Jorman** [comment]
> IIUC there is a way (in newer versions) to check if torrent is private in language-agnostic way https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)
> 
> ![изображение](https://private-user-images.githubusercontent.com/5204968/358926018-b46b8a71-0810-463e-ae78-5213d08c6fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMDI5MDEsIm5iZiI6MTcyNDAwMjYwMSwicGF0aCI6Ii81MjA0OTY4LzM1ODkyNjAxOC1iNDZiOGE3MS0wODEwLTQ2M2UtYWU3OC01MjEzZDA4YzZmYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTczNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQwMGY1MGM2YTA1NGY5MDBkYzgzZWNkNDFhZGJjMTA5MTYwYTRiNDNjYzcyYjU1MGNlNzVmOWZhMWQwYmI2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bldUmdHsbuNrsA5We_Q-HVXP3FRlbJ-5uY7BJlqAO_c)

Perfect, I can plan one fix to this!

**Comment by soredake** [comment]
> Hi, I think the problem is the sh interpreter, this script is made for bash, not for sh.
> Try to call it without any interpreter, so it will use the bash one that is specified

Unfortunately, it's not helping, the problem is in language check.

**Comment by Jorman** [comment]
@soredake 
I made a pull request for this, try and let me know if resolve this problem

**Comment by Jorman** [comment]
@ineednewpajamas 
One off-topic question, do you think it is possible to "transpose" the script and make a Python version? I saw you're pretty good with python

**Comment by ineednewpajamas** [comment]
Is it possible? Yes.
I'm not that great with python but fluent enough to write basic scripts and contribute to others. I know there is [qbittorrent-api](https://github.com/rmartin16/qbittorrent-api) or just using requests with the WebAPI you're already using.

I could take a look as I have time but that might take a while.

**Comment by soredake** [comment]
@Jorman now it's correctly recognized private torrent with this pr, thanks!

**Comment by Jorman** [comment]
> @Jorman now it's correctly recognized private torrent with this pr, thanks!

Good to know, the new functionality from qBittorrent guy, is also pretty new, just in July they added this!

**Comment by Jorman** [comment]
> Is it possible? Yes. I'm not that great with python but fluent enough to write basic scripts and contribute to others. I know there is [qbittorrent-api](https://github.com/rmartin16/qbittorrent-api) or just using requests with the WebAPI you're already using.
> 
> I could take a look as I have time but that might take a while.

No hurry and no obligation, on the contrary, I thank you immensely if you can look at it, then if you need information about the script just ask, I didn't put comments in every single line, so maybe it may seem "hostile" in some places.
I'm asking because I don't know how to do it, python I don't know much about it and still object-oriented programming doesn't get into my head, I have a hard time appreciating its value for these scripts, I mean, it seems to me that simple if else logic is more than enough to handle it, then maybe you'll be able to change my mind, basically I don't see the practical side, except to turn the script into a more "universal" version suitable for all machines, both windows and Linux.
I saw that there is a dedicated library, I looked at it just a little bit, maybe I will try to play with it too, although I need an AI assistant to do it, because I know what I want to do but in python I don't know exactly how to do it

How do you see it?

**Comment by ineednewpajamas** [comment]
@Jorman Feel free to open a generic issue here and we can use it to discuss stuff without cluttering this issue: https://github.com/ineednewpajamas/Jorman_Scripts/issues
