### ISSUE TITLE
Best procedure recommendations for qbittorrent & public trackers with these scripts?

### ISSUE THREAD

**Issue by gggirlgeek** [Jorman/Scripts#39]
Hi,

Thanks for the scripts! I am going to use the Powershell for qBt on Windows 10. I need opinions on best procedures replacing public trackers on an ongoing basis with a scheduled task.

Questions:

-Is it generally best to delete or clear the current trackers? Does it hurt anything to leave them, or make checking slower? I'm nervous a tracker that is needed might get deleted. I use about 3 different RSS public sources, and 7 different search engine sources, but all of them are the usual main stream public ones.

-Will having too many trackers in the torrent slow down the checking process? In other words, if I use the "All" list, as apposed to the "best" list, or add all IP's plus all URL's, will it slow down checking, especially with 4000+ torrents (5 downloads active).

-Should I add the other mirrors as backup? Will that create duplicates and slow down checking, or does qBittorrent eliminate duplicates? (Also, the repeated scheduled task won't keep adding duplicates, will it?)

-Should I put both the https & the http lists? (I am using both udp and https trackers now, and TCP/UDP mode, and "Allow Encryption" mode, all public trackers. I haven't noticed whether http connects better than https. Anyone else?)

In case it matters, I am using Windscribe VPN, with their Robert DNS. Alternate DNS is Adguard and Quad9 or CtrolD unfiltered, which I tell Windscribe to use sometimes.

**Comment by Jorman** [comment]
Ciao @gggirlgeek 

There is a PowerShell adaptation and I see you found it, I left the post open specifically. I try to give my interpretation/answer to your questions and keep in mind that I always talk about the bash script, because its adaptation in PowerShell may not have that functionality/feature

> Is it generally best to delete or clear the current trackers? Does it hurt anything to leave them, or make checking slower? I'm nervous a tracker that is needed might get deleted. I use about 3 different RSS public sources, and 7 different search engine sources, but all of them are the usual main stream public ones.

The script has two features, one built-in and one to be called with an appropriate argument, you find everything by running the script without arguments. The script by default saves existing trackers and adds them to the downloaded trackers. Otherwise, via special command, it deletes the existing trackers and adds only the downloaded ones.
I personally prefer to keep the original trackers, it costs me nothing, I also personally use a script that at regular intervals checks for broken trackers and deletes them, so that I don't have useless trackers. Always keep in mind that normally, but maybe your configuration is different, DHT etc. are always active

> Will having too many trackers in the torrent slow down the checking process? In other words, if I use the "All" list, as apposed to the "best" list, or add all IP's plus all URL's, will it slow down checking, especially with 4000+ torrents (5 downloads active).

It is always better to have a few trackers and good ones, rather than many but useless ones. Of course, having too many trackers, for so many torrents, means having long times. I am not so expert in this subject though, I think it also depends so much on how the client is programmed you could also look on the channels dedicated to qBittorrent to see how it handles torrents, so it can give you a better idea about this question

> Should I add the other mirrors as backup? Will that create duplicates and slow down checking, or does qBittorrent eliminate duplicates? (Also, the repeated scheduled task won't keep adding duplicates, will it?)

Personally, I never add trackers more than once, never planning to add trackers regularly. If a torrent is dying with no sources, it is unlikely that continually adding trackers over time will cause it to become findable, but if one has no problems with space and time, it costs nothing to try. The script does not insert duplicates, trackers before being inserted are checked and duplicate trackers deleted

> Should I put both the https & the http lists? (I am using both udp and https trackers now, and TCP/UDP mode, and "Allow Encryption" mode, all public trackers. I haven't noticed whether http connects better than https. Anyone else?)

Other question more suitable for qBittorrent channels, in general I would say it doesn't make a difference, the tracker is nothing but a point where other people connected like you, they exchange information about torrents, as happened with ed2k servers, and again, let's remember that there is DHT etc, which help a lot

> In case it matters, I am using Windscribe VPN, with their Robert DNS. Alternate DNS is Adguard and Quad9 or CtrolD unfiltered, which I tell Windscribe to use sometimes.

Perhaps the most important thing in this case, is to have an open port to the outside, because if you get a "low" ID as happened on eMule for instance, you're going to have some limitations, generally slowdowns

**Comment by gggirlgeek** [comment]
Thank you very much for the advice. The Powershell script is working nicely. I am using it regularly, though, because I want to make sure I am getting fresh trackers updated when dead ones go down. I have noticed a lot of torrents that have no seeds after just a week lately (a big topic, I know) so I want to make sure my seeds are getting broadcast to live new trackers as they come up.  It also may help with old torrents I'm having trouble manually downloading. I have the powershell script in my Task Scheduler, running once a day. Later I will think about using the modified version of qBittorrent, that is able to add trackers from a URL, automatically, but right now I need to use the official version, for various reasons.

For others who may come accross this: So far, using thThank you very much for the advice. The Powershell script is working nicely. I am using it regularly, though, because I want to make sure I am getting fresh trackers updated when dead ones go down. I have noticed a lot of torrents that have no seeds after just a week lately (a big topic, I know) so I want to make sure my seeds are getting broadcast to live new trackers as they come up.  It also may help with old torrents I'm having trouble manually downloading. I have the powershell script in my Task Scheduler, running once a day. Later I will think about using the modified version of qBittorrent, that is able to add trackers from a URL, automatically, but right now I need to use the official version, for various reasons.

For others who may come accross this: So far, using [this](https://www.mypdns.org/trackit/trackers.txt) well-maintained link of trackers in the script works nicely (always t
he same, or more, seeds than the embedded trackers in my few tests). I've also decided to add the IP addresses from [this one](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best_ip.txt) for the heck of it.

I don't see a script here to remove "not working" trackers from all torrents, and it would probably not be worth the trouble to adapt it to Powershell anyway. But great idea. Let us know if cleaning them out seems to help you. is well-maintained link of trackers in the script works nicely (always t
he same, or more, seeds than the embedded trackers in my few tests). I've also decided to add the IP addresses from this one for the heck of it.

I don't see a script here to remove "not working" trackers from all torrents, and it would probably not be worth the trouble to adapt it to Powershell anyway. But great idea. Let us know if cleaning them out seems to help you.
